### ISSUE TITLE
500k resistors on igniter board?

### ISSUE THREAD

**Issue by marccardinal** [shanet/Osprey#22]
Good afternoon,

Can you explain the purpose of the 500k ohm resistors on the igniter board? They seem to be applying a constant (but minimal) load on the battery and look optional no?

Thanks!

**Comment by shanet** [comment]
That's right, they are not strictly required. They are present to act as a safety check on slowly discharging the capacitors after the battery is disconnected to prevent inadvertent ignitions of the igniters.

**Comment by marccardinal** [comment]
Oh that makes sense! Thanks for the explanation :)
